# Generated by Django 5.2.7 on 2025-10-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='photos/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Camera', 'Camera'), ('Screenshot', 'Screenshot'), ('Album', 'Album')], default='Camera', max_length=50)),
            ],
        ),
    ]
