# Generated by Django 5.2.7 on 2025-10-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
